# Exported from Render on 2025-06-26T15:50:49Z
services:
- type: web
  name: 'Microservice-product_service '
  runtime: docker
  repo: https://github.com/Deva-Profile/Microservice
  plan: free
  envVars:
  - key: CLOUDINARY_API_SECRET
    sync: false
  - key: CLOUDINARY_API_KEY
    sync: false
  - key: CLOUDINARY_CLOUD_NAME
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_NAME
    sync: false
  - key: ALLOWED_HOSTS
    sync: false
  - key: DEBUG
    sync: false
  - key: SECRET_KEY
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
  rootDir: seedapp_microservices/product_service/
- type: web
  name: Microservice-user_service
  runtime: docker
  repo: https://github.com/Deva-Profile/Microservice
  plan: free
  envVars:
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_NAME
    sync: false
  - key: ALLOWED_HOSTS
    sync: false
  - key: DEBUG
    sync: false
  - key: SECRET_KEY
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
  rootDir: seedapp_microservices/user_service
version: "1"
