# Generated by Django 4.2.20 on 2025-04-09 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_contact', models.CharField(max_length=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_option', models.CharField(choices=[('Advance', 'Advance'), ('Full', 'Full Payment')], default='Advance', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
